name: Deploy Firebase Hosting

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]	# 複数バージョンを指定可能 [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        sh -c './bin/build.sh'

    - name: Deploy to Firebase Hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        sh -c './bin/deploy_firebase.sh'

    - name: Slack Notification2
      env:
        SLACK_CHANNEL: 05_ci_cd
        SLACK_ICON: https://mosapride.com/wp-content/uploads/2017/06/touchicon-180.png
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        sh -c './bin/slack.sh'